version: "3.1"
services:

  jenkins:
    container_name: jenkins
    # image: jenkins:2.60.3
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "50000:50000"
    # restart: always
    # environment:
    volumes:
      - ./data:/var/jenkins_home